In [1]:
#1.1.1.1

import numpy as np

def sigmoid(x : float) -> float:
    return 1/(1 + np.exp(-x))

class Neuron:

    weights : np.array
    bias : float

    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs) -> float:
        output = np.dot(self.weights, inputs) + self.bias
        return sigmoid(output)

class OurNeuralNetwork:
    
    h1 : Neuron
    h2 : Neuron
    h3 : Neuron
    o1 : Neuron

    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0

        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)

    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h2.feedforward(x)

        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1

network = OurNeuralNetwork()
x = np.array([2, 3, 1])
print(network.feedforward(x))


0.8067238139969796


In [27]:
#1.1.1.2

import numpy as np

def sigmoid(x : float) -> float:
    return 1/(1 + np.exp(-x))

class OurNeuralNetwork:
    
    h1 : Neuron
    h2 : Neuron
    o1 : Neuron
    o2 : Neuron

    def __init__(self):
        weights = np.array([1, 0])
        bias = 1

        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
        self.o2 = Neuron(weights, bias)

    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)

        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2]))
        out_o2 = self.o1.feedforward(np.array([out_h1, out_h2]))
        return out_o1, out_o2

network = OurNeuralNetwork()
x = np.array([2, 3])
print(network.feedforward(x))

(0.8757270529783324, 0.8757270529783324)


In [25]:
#1.1.2.1

def tanh(x):
    return np.tanh(x)

class Neuron:

    weights : np.array
    bias : float

    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs) -> float:
        output = np.dot(self.weights, inputs) + self.bias
        return tanh(output)

network = OurNeuralNetwork()
x = np.array([2, 3])
print(network.feedforward(x))

(0.9636765235959711, 0.9636765235959711)


In [28]:
#1.1.2.2

def relu(x):
    if x < 0: 
        return 0
    else:
        return x

class Neuron:

    weights : np.array
    bias : float

    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs) -> float:
        output = np.dot(self.weights, inputs) + self.bias
        return relu(output)

network = OurNeuralNetwork()
x = np.array([2, 3])
print(network.feedforward(x))

(4, 4)


In [75]:
# 1.2.1

import numpy as np
import pandas as pd

csv_file = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')
csv_file.shape
digits = csv_file.to_numpy()
x_digits, y_digits = np.array([[float(i) for i in data if i != data[-1]] for data in digits]), np.array([data[-1] for data in digits])
print('Dataset Sizes : ', x_digits.shape, y_digits.shape)

from sklearn.model_selection import train_test_split

random_state = 95

x_train, x_test, y_train, y_test = train_test_split(x_digits, y_digits,
train_size=0.80, test_size=0.20, stratify=Y_digits, random_state=random_state)

from sklearn.neural_network import MLPClassifier

mlp_classifier = MLPClassifier(random_state=random_state, max_iter=400, hidden_layer_sizes=(160, 80, 40, ))
mlp_classifier.fit(x_train, y_train)

y_preds = mlp_classifier.predict(x_test)

print(y_preds[:15])

print(y_test[:15])

print('Test Accuracy : %.3f'%mlp_classifier.score(x_test, y_test))

print('Training Accuracy : %.3f'%mlp_classifier.score(x_train, y_train))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

conf_mat = confusion_matrix(y_test, y_preds)
print(conf_mat)

print("Loss : ", mlp_classifier.loss_)
print("Number of Coefs : ", len(mlp_classifier.coefs_))
print("Number of Intercepts : ", len(mlp_classifier.intercepts_))
print("Number of Iterations for Which Estimator Ran : ", mlp_classifier.n_iter_)
print("Name of Output Layer Activation Function : ", mlp_classifier.out_activation_)

Dataset Sizes :  (150, 4) (150,)
['Virginica' 'Virginica' 'Versicolor' 'Virginica' 'Setosa' 'Setosa'
 'Versicolor' 'Virginica' 'Virginica' 'Setosa' 'Virginica' 'Setosa'
 'Virginica' 'Versicolor' 'Versicolor']
['Virginica' 'Virginica' 'Versicolor' 'Virginica' 'Setosa' 'Setosa'
 'Versicolor' 'Virginica' 'Virginica' 'Setosa' 'Virginica' 'Setosa'
 'Virginica' 'Versicolor' 'Versicolor']
Test Accuracy : 0.967
Training Accuracy : 1.000
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
Loss :  0.011226155153042023
Number of Coefs :  4
Number of Intercepts :  4
Number of Iterations for Which Estimator Ran :  308
Name of Output Layer Activation Function :  softmax


In [76]:
# 1.2.1

import numpy as np
import pandas as pd

csv_file = pd.read_csv('https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv')
csv_file.shape
digits = csv_file.to_numpy()
x_digits, y_digits = np.array([[float(i) for i in data if i != data[-1]] for data in digits]), np.array([float(data[-1]) for data in digits])
print('Dataset Sizes : ', x_digits.shape, y_digits.shape)

from sklearn.model_selection import train_test_split

random_state = 123

x_train, x_test, y_train, y_test = train_test_split(x_digits, y_digits,
train_size=0.80, test_size=0.20, random_state=random_state)

from sklearn.neural_network import MLPRegressor

mlp_regressor = MLPRegressor(random_state=random_state, max_iter=20000)
mlp_regressor.fit(x_train, y_train)

y_preds = mlp_regressor.predict(x_test)

print(Y_preds[:10])

print(Y_test[:10])

print('Test Accuracy : %.3f'%mlp_regressor.score(x_test, y_test))

print('Training Accuracy : %.3f'%mlp_regressor.score(x_train, y_train))

print("Loss : ", mlp_regressor.loss_)
print("Number of Coefs : ", len(mlp_regressor.coefs_))
print("Number of Intercepts : ", len(mlp_regressor.intercepts_))
print("Number of Iterations for Which Estimator Ran : ", mlp_regressor.n_iter_)
print("Name of Output Layer Activation Function : ", mlp_regressor.out_activation_)

Dataset Sizes :  (30, 1) (30,)
[ 50570.93568673 133554.81759904  47160.65137704 122186.90619014
  50570.93568673 123323.66762671]
[ 54445. 121872.  56642. 116969.  64445. 112635.]
Test Accuracy : 0.891
Training Accuracy : 0.917
Loss :  26692614.428927224
Number of Coefs :  2
Number of Intercepts :  2
Number of Iterations for Which Estimator Ran :  20000
Name of Output Layer Activation Function :  identity


c:\Users\TEMP.LAPTOP-989782I0.002\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20000) reached and the optimization hasn't converged yet.
  warnings.warn(
