In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
# 1.3.1

line = [0 if x % 2 == 0 else 1 for x in range(8)]
a = np.array([line if y % 2 == 0 else line[::-1] for y in range(8)])
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
# 1.3.2

a = np.array([np.arange(0, 5) for x in range(5)])
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [4]:
# 1.3.3

a = np.random.random((3, 3, 3))
print(a)

[[[0.13749516 0.49022164 0.39720783]
  [0.94393331 0.50368678 0.99288142]
  [0.55783765 0.88847426 0.34757712]]

 [[0.86693886 0.77611284 0.29198724]
  [0.72217799 0.06734753 0.27284672]
  [0.71868799 0.86495727 0.89821794]]

 [[0.55155022 0.04897403 0.44698889]
  [0.79658619 0.31765905 0.12161218]
  [0.14688176 0.29344999 0.79616903]]]


In [5]:
# 1.3.4

a = np.zeros((4, 4))
for i in range(a.shape[0]):
    a[i] = np.array([1] + list(a[i][1: -1:]) + [1])
print(a)

[[1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]]


In [6]:
# 1.3.5

a = np.random.random(10)
a = np.sort(a)
print(a)

[0.05731736 0.12974211 0.32356109 0.33062006 0.40674108 0.57742639
 0.72842781 0.90747082 0.95323178 0.98428683]


In [7]:
# 1.3.6

a = np.random.random((5, 5))
print(a)
print()
print(f'shape = { a.shape }')
print(f'size = { a.size }')
print(f'ndim = { a.ndim }')

[[0.93746609 0.94979329 0.39748979 0.46088069 0.76358184]
 [0.04615725 0.74405708 0.99027086 0.08857372 0.69948735]
 [0.09321564 0.07358141 0.87928997 0.20158981 0.51360995]
 [0.87322518 0.4930085  0.32494555 0.64910216 0.6140238 ]
 [0.5325525  0.69215482 0.86849139 0.04586204 0.88927499]]

shape = (5, 5)
size = 25
ndim = 2


In [24]:
# 2.3.1

a = pd.Series([i for i in range(5)])
b = pd.Series([i + 6 for i in range(5)])
print(sum([(b[i]- a[i])**2 for i in range(len(a))])**0.5)

13.416407864998739


In [11]:
# 2.3.2

url = 'https://raw.githubusercontent.com/akmand/datasets/main/vehicle.csv'
vehicle = pd.read_csv(url)

In [12]:
# 2.3.3

vehicle.head(2)

1   2   3    4   5   6    7   8   9   10   11   12   13  14  15  16   17  \
0  95  48  83  178  72  10  162  42  20  159  176  379  184  70   6  16  187   
1  91  41  84  141  57   9  149  45  19  143  170  330  158  72   9  14  189   

    18   19  
0  197  van  
1  199  van

In [13]:
vehicle.tail(3)

1   2    3    4   5   6    7   8   9   10   11   12   13  14  15  16  \
843  106  54  101  222  67  12  222  30  25  173  228  721  200  70   3   4   
844   86  36   78  146  58   7  135  50  18  124  155  270  148  66   0  25   
845   85  36   66  123  55   5  120  56  17  128  140  212  131  73   1  18   

      17   18    19  
843  187  201  saab  
844  190  195  saab  
845  186  190   van

In [14]:
vehicle.shape

(846, 19)

In [15]:
vehicle.describe()

1           2           3           4           5           6  \
count  846.000000  846.000000  846.000000  846.000000  846.000000  846.000000   
mean    93.678487   44.861702   82.088652  168.940898   61.693853    8.567376   
std      8.234474    6.169866   15.771533   33.472183    7.888251    4.601217   
min     73.000000   33.000000   40.000000  104.000000   47.000000    2.000000   
25%     87.000000   40.000000   70.000000  141.000000   57.000000    7.000000   
50%     93.000000   44.000000   80.000000  167.000000   61.000000    8.000000   
75%    100.000000   49.000000   98.000000  195.000000   65.000000   10.000000   
max    119.000000   59.000000  112.000000  333.000000  138.000000   55.000000   

                7           8           9          10          11  \
count  846.000000  846.000000  846.000000  846.000000  846.000000   
mean   168.839243   40.933806   20.582742  147.998818  188.625296   
std     33.244978    7.811560    2.592138   14.515652   31.394837   
min    112.000000   26.000000   17.000000  118.000000  130.000000   
25%    146.250000   33.000000   19.000000  137.000000  167.000000   
50%    157.000000   43.000000   20.000000  146.000000  178.500000   
75%    198.000000   46.000000   23.000000  159.000000  217.000000   
max    265.000000   61.000000   29.000000  188.000000  320.000000   

                12         13          14          15          16          17  \
count   846.000000  846.00000  846.000000  846.000000  846.000000  846.000000   
mean    439.911348  174.70331   72.462175    6.377069   12.599291  188.932624   
std     176.692614   32.54649    7.486974    4.918353    8.931240    6.163949   
min     184.000000  109.00000   59.000000    0.000000    0.000000  176.000000   
25%     318.250000  149.00000   67.000000    2.000000    5.000000  184.000000   
50%     364.000000  173.00000   71.500000    6.000000   11.000000  188.000000   
75%     587.000000  198.00000   75.000000    9.000000   19.000000  193.000000   
max    1018.000000  268.00000  135.000000   22.000000   41.000000  206.000000   

               18  
count  846.000000  
mean   195.632388  
std      7.438797  
min    181.000000  
25%    190.250000  
50%    197.000000  
75%    201.000000  
max    211.000000

In [16]:
vehicle.iloc[1:4]

1   2    3    4   5   6    7   8   9   10   11   12   13  14  15  16  \
1   91  41   84  141  57   9  149  45  19  143  170  330  158  72   9  14   
2  104  50  106  209  66  10  207  32  23  158  223  635  220  73  14   9   
3   93  41   82  159  63   9  144  46  19  143  160  309  127  63   6  10   

    17   18    19  
1  189  199   van  
2  188  196  saab  
3  199  207   van

In [17]:
vehicle.loc[1:4]

1   2    3    4    5   6    7   8   9   10   11   12   13   14  15  16  \
1   91  41   84  141   57   9  149  45  19  143  170  330  158   72   9  14   
2  104  50  106  209   66  10  207  32  23  158  223  635  220   73  14   9   
3   93  41   82  159   63   9  144  46  19  143  160  309  127   63   6  10   
4   85  44   70  205  103  52  149  45  19  144  241  325  188  127   9  11   

    17   18    19  
1  189  199   van  
2  188  196  saab  
3  199  207   van  
4  180  183   bus

In [16]:
import pandas as pd
from sklearn import preprocessing as prepr

In [17]:
# 3.3.2

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
iris = pd.read_csv(url)

minimax = prepr.MinMaxScaler(feature_range = (0,1))
scaler = prepr.StandardScaler()
iris[['sepal_length_cm']] = minimax.fit_transform(iris[['sepal_length_cm']])
iris[['sepal_width_cm']] = scaler.fit_transform(iris[['sepal_width_cm']])
print(iris.head(5))

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa
